### ISSUE TITLE
client: socat leaves files on unclean exit

### ISSUE THREAD

**Issue by torarnv** [home-assistant-libs/tellcore-net#2]
If the TellCoreClient and its child `socat` processes are shut down in a non-clean way, e.g if a Docker container is stopped/killed, it may leave files in /tmp, which then prevents starting up the client the next time. Manually running socat in this situation shows:

`2017/12/10 22:13:31 socat[168] E "/tmp/TelldusEvents" exists`

I don't know if there's a way we can detect a shutdown and always clean up, so the better approach is probably to delete the file before firing up socat:

```
            file = "/tmp/" + telldus
            try:
                os.remove(file)
            except FileNotFoundError:
                pass
            args = shlex.split(SOCAT_CLIENT.format(
                file=file, host=self.host, port=port))
```

Related, would it make sense to pass stderr (and stdout) to their respective FDs, instead of DEVNULL? Otherwise it's hard to pick up any errors socat is emitting. Dunno how to best feed that into the Home Assistant logs.

**Comment by pvizeli** [comment]
I think we should remove this files on stop. So if you shutdown a the container, it will be cleanup. If we remove it on start, it could be kill a running instance and make deadlock with posix filelock.

**Comment by torarnv** [comment]
Doesn’t that assume we are able to shut down home assistant itself in a clean way, since that’s where the client is running?

 That is not always the case for me, due to HA taking a while to shut down, and Docker-compose then explicitly killing it eg. Or it can happen in other ways too. Resulting in tellstick failing on next start without any info why or how to correct it. 

Isn’t there a way to detect whether or not a file is open for writing via lsof or something? What happens today if telldusd is running and tellcore-net client is initialized?

- Tor Arne

**Comment by pvizeli** [comment]
Fix with https://github.com/pvizeli/tellcore-net/commit/3feafc3e921ef94671da7411fb163714fbf2b2bb

**Comment by torarnv** [comment]
Sweet, thanks!
