### ISSUE TITLE
tellstick addon 0.4 not working in 0.60.0 of home assistant (hass.io)

### ISSUE THREAD

**Issue by widdde** [home-assistant-libs/tellcore-net#4]
After update to version 0.60.0 of home assistant and version 0.4 of tellstick addon the addon no longer works on my setup.
Log looks like this:
`2017-12-29 01:14:19 ERROR (MainThread) [homeassistant.setup] Error during setup of component tellstick
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 193, in _async_setup_component
    component.setup, hass, processed_config)
  File "/usr/lib/python3.6/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/tellstick.py", line 99, in setup
    tellcore_devices = tellcore_lib.devices()
  File "/usr/lib/python3.6/site-packages/tellcore/telldus.py", line 173, in devices
    count = self.lib.tdGetNumberOfDevices()
  File "/usr/lib/python3.6/site-packages/tellcore/library.py", line 257, in check_int_result
    raise TelldusError(result)
tellcore.library.TelldusError: Could not connect to the Telldus Service (-6)`

Log for tellstick addon look like this:
`starting version 3.2.4
[Info] Initialize the tellstick configuration
[Info] Exposing sockets and loading service
[Info] Starting event listener
telldusd daemon starting up
Connecting to TellStick (1781/C31) with serial XYXYXYXY`

I have seen other people having the same problem and I have not found the reason yet, therefor filing this bug.

EDIT:
My configuration.yaml looks like this and I have not touched the config since the integration broke:
`tellstick:
  host: core-tellstick
  port: [50800, 50801]
  signal_repetitions: 3

switch:
  - platform: tellstick`
(Yaml formatted of course, which you don't see here)

**Comment by endor-force** [comment]
Based on some checks and tries on similar hardware (pi 2 and Tellstick duo) i have not succeeded to reproduce the error.
It would be great if we can add logging on debug level to catch any output from socat.

I have guided two of the users reporting the problem and ruled out add-on, hardware or configuration issues.
My guess is that the sockets are not fully established before tellstick component continue loading and tries to interact with the service.

Would there be any way to add a wait timeout/check for the sockets to be loaded?

**Comment by widdde** [comment]
Your guess can definitely be right endor-force, before upgrading to 0.60.0 I had some boots of HA that worked perfectly and some where I got the tellstick configuration error.
I can communicate with the tellstick through the services under developer settings, after HA has started.

I am running HA on a pi 3 by the way (Hass.io image)

**Comment by pvizeli** [comment]
We can add a sleep and a check if the socket exists before we go back...

**Comment by endor-force** [comment]
@widdde Please try now.
Seems like 0.79 is out. (Check in your hass.io advanced settings) if it is updated on your device.

**Comment by widdde** [comment]
@endor-force 
Version of what? =)

My versions: 

Supervisor:
Version: 0.80
Home Assistant:
Current version: 0.60.1

Tellstick addon:
version: 0.4

When restarting my pi:
Invalid Config
The following components and platforms could not be setup:
* tellstick

**Comment by endor-force** [comment]
@widdde the problem seems related to hassio internal DNS.
You can workaround the issue temporary by entering the internal IP of core-tellstick in the configuration.yaml file, for `host: 172.30.33.0`

The IP could potentially differ on your system.. give it a try as a workaround until the root cause has been solved.

**Comment by endor-force** [comment]
This should now be solved in hass.io 0.81 by @pvizeli, update your supervisor, use core-tellstick for host and reboot host.
